# config.yaml

# 项目的根目录路径
preprocess_data_dir: "./data/preprocess"
data_dir: "barricade"

pitch_angles:
  - pitch0-30
  - pitch30-50
  - pitch50-80

categories:
  0: "excavator"
  1: "plastic_fence"
  2: "steel_fence"
  3: "opening"
  4: "person"

split_ratio:
  0.7